name: Development Workflow 3.8

on:
  pull_request:
    branches:
      - 'master'

jobs:
  run_pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -vv

  deploy_heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          google_api_key: ${{secrets.GOOGLE_API_KEY}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "maxproject-3-dev" #Must be unique in Heroku
          heroku_email: "ml644@njit.edu"
          usedocker: true